const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {makeProject,treeDigest}=require('./helpers/project.cjs');
const ok=r=>assert.equal(r.status,0,r.stderr+'\n'+r.stdout);
function setup(t,targets='codex'){const p=makeProject(t),f=p.selection(['alpha']);ok(p.run('init','--file',f,'--target',targets));return p;}
test('missing baseline is preserved by init but cannot authorize update',t=>{const p=setup(t);fs.unlinkSync(path.join(p.path,'.skillsman/state.json'));const before=treeDigest(p.path);ok(p.run('init','--file',path.join(p.path,'.skillsman/skills.yaml'),'--target','codex'));assert.equal(treeDigest(p.path),before);const r=p.run('update','--target','codex');assert.notEqual(r.status,0);assert.match(r.stderr,/BASELINE_UNKNOWN/);assert.equal(treeDigest(p.path),before);});
test('removed upstream selection and skipped installation never expand or replace intent',t=>{const p=setup(t);delete p.settings.catalog['example/kit'].alpha;p.configure({});const before=treeDigest(p.path);const r=p.run('update','--target','codex');assert.notEqual(r.status,0);assert.equal(treeDigest(p.path),before);assert(!p.calls().some(c=>c.args[0]==='update'));});
test('zero exit without installed files cannot become a verified success',t=>{const p=makeProject(t),f=p.selection(['alpha']);p.configure({skipNames:['alpha']});const r=p.run('init','--file',f,'--target','codex');assert.notEqual(r.status,0);assert.match(r.stderr,/unresolved alpha/);assert(!fs.existsSync(path.join(p.path,'.skillsman/state.json')));});
test('shared content update blocks a partial scope; all only refreshes existing associations',t=>{const p=setup(t,'codex,claude');const before=treeDigest(p.path);const denied=p.run('update','--target','codex','--dry-run');assert.notEqual(denied.status,0);assert.match(denied.stderr,/SHARED_IMPACT/);assert.equal(treeDigest(p.path),before);ok(p.run('update','--target','all'));assert(!fs.existsSync(path.join(p.path,'.cursor/skills/alpha')));const last=p.calls().filter(c=>c.cwd===p.path&&c.args[0]==='add').at(-1);assert(!last.args.includes('*'));});
test('outside selected content remains byte identical through update',t=>{const p=setup(t);const dir=path.join(p.path,'.agents/skills/delta');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'SKILL.md'),'---\nname: delta\ndescription: Extra\n---\nuntouched');const before=treeDigest(dir);p.settings.catalog['example/kit'].alpha='v2';p.configure({});ok(p.run('update','--target','codex'));assert.equal(treeDigest(dir),before);});
test('missing selected file and corrupted lock do not become installation permission',t=>{const p=setup(t);fs.unlinkSync(path.join(p.path,'.agents/skills/alpha/SKILL.md'));let before=treeDigest(p.path);assert.notEqual(p.run('update','--target','codex').status,0);assert.equal(treeDigest(p.path),before);fs.writeFileSync(path.join(p.path,'skills-lock.json'),'{broken');before=treeDigest(p.path);assert.notEqual(p.run('update','--target','codex').status,0);assert.equal(treeDigest(p.path),before);});

test('post-preview content drift is reported and does not replace the old baseline',t=>{const p=setup(t),state=path.join(p.path,'.skillsman/state.json'),before=fs.readFileSync(state,'utf8');p.configure({driftInProject:p.path});const r=p.run('update','--target','codex');assert.notEqual(r.status,0);assert.match(r.stderr,/upstream content changed/);assert.equal(fs.readFileSync(state,'utf8'),before);});
test('unexpected installed names are never reported as a successful selected install',t=>{const p=makeProject(t),f=p.selection(['alpha']);p.configure({extraName:'gamma'});const r=p.run('init','--file',f,'--target','codex');assert.notEqual(r.status,0);assert.match(r.stderr,/unrequested|unexpected/i);assert(!fs.existsSync(path.join(p.path,'.skillsman/state.json')));});
